CREATE TABLE IF NOT EXISTS Files (
  id     INTEGER PRIMARY KEY NOT NULL,
  path   TEXT NOT NULL,
  md5    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Relationship (
  id   INTEGER PRIMARY KEY NOT NULL,
  src  INTEGER,
  dst  INTEGER,

  FOREIGN KEY(src) REFERENCES Files(id),
  FOREIGN KEY(dst) REFERENCES Files(id)
);
